# Generated by Django 4.2.9 on 2024-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
